### ISSUE TITLE
Voxelise dependency

### ISSUE THREAD

**Issue by petterssonjonas** [MightyBucket/AMGeneration#1]
Awesome project, cant wait to use it!
I installed it on win10 according to instructions, however the voxelise module is unresolved and i cannot figure out what package it refers to.

```
17:24:36  No module named 'Voxelise'
17:24:36  Traceback (most recent call last):
  File "<string>", line 11, in Initialize
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\jpett\AppData\Roaming\FreeCAD\Mod\AMGeneration2\Refine.py", line 11, in <module>
    import Voxelise
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

```

**Comment by MightyBucket** [comment]
Hey, thanks for spotting that! It's a module that I forgot to upload. It should work now :)

**Comment by MightyBucket** [comment]
Also I’m interested to know how you found out about this project. Right now its too buggy and unintuitive for anyone to use in the real world but I’d love to know what you think of it!

It would be great to have any feedback, little or big. If you can, please shoot me an email at rahuljhuree@hotmail.co.uk :)
